tasks:
  - name: DockerCompose
    init: |
      export APP_URL=`gp url 8080 | sed 's~https://~~'`
      docker-compose up
  - name: Install
    init: gp ports await 8080 && APP_URL=`gp url 8080 | sed 's~https://~~'` ./install.sh

ports:
  - port: 8080
    onOpen: open-preview

vscode:
  extensions:
    - ms-azuretools.vscode-docker
